services:
  frontend:
    build:
      context: ./frontend
    image: edwa-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - frontend-network
  
  user-service:
    build:
      context: ./services/user-service
    image: edwa-user-service:latest
    ports:
      - "8081:8080"
    networks:
      - backend-network
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-network

  tweet-service:
    depends_on: 
      - redis
    build:
      context: ./services/tweet-service
    image: edwa-tweet-service:latest
    ports:
      - "3001:3000"
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
